name: build

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: "KernelSU type"
        required: true
        default: "KSU"
        type: choice
        options:
          - KSU
          - NON_KSU

      rom_type:
        description: "ROM base"
        required: true
        default: "MIUI"
        type: choice
        options:
          - AOSP
          - MIUI

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KSU_TYPE: ${{ github.event.inputs.ksu_type }}
      ROM_TYPE: ${{ github.event.inputs.rom_type }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare timezone
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Jakarta date '+%d%m%Y-%H%M')" >> $GITHUB_ENV
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

      - name: Install Dependencies
        run: |
          sudo apt -yqq update
          sudo apt -yqq install git make bc bison openssl curl zip kmod cpio flex \
            libelf-dev libssl-dev libtfm-dev wget device-tree-compiler \
            ca-certificates python3 binutils \
            binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi xz-utils

      - name: Fetch Toolchains
        run: |
          mkdir -p "$HOME/clang"
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz \
            | tar -xz -C "$HOME/clang"

      - name: Apply build type
        run: |
          if [ "$KSU_TYPE" = "KSU" ]; then
            git clone -b legacy https://github.com/sidex15/KernelSU-Next.git
          fi
          apply_panel_dimensions() {
              local w=$1 h=$2
              local files=(
                  "arch/arm64/boot/dts/qcom/xiaomi/sweet/dsi-panel-k6-38-0e-0b-fhd-dsc-video.dtsi"
                  "arch/arm64/boot/dts/qcom/xiaomi/sweet/dsi-panel-k6-38-0c-0a-fhd-dsc-video.dtsi"
              )
              echo -e "${CYAN}Setting panel size → ${w} × ${h} mm${NC}"
              for f in "${files[@]}"; do
                  [ -f "$f" ] && sed -i "s/\(qcom,mdss-pan-physical-width-dimension[[:space:]]*=[[:space:]]*< *\)[0-9]\+/\1${w}/" "$f"
                  [ -f "$f" ] && sed -i "s/\(qcom,mdss-pan-physical-height-dimension[[:space:]]*=[[:space:]]*< *\)[0-9]\+/\1${h}/" "$f"
              done
          }
          if [ "$ROM_TYPE" = "MIUI" ]; then
            echo ">> MIUI-specific config"
            apply_panel_dimensions 695 1546
          else
            apply_panel_dimensions 70 155
          fi

      - name: Build Kernel
        run: |
          export PATH="$HOME/clang/bin:$PATH"
          export KBUILD_COMPILER_STRING=$("$HOME"/clang/bin/clang --version | head -n 1 | sed 's/  */ /g')
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          export KBUILD_BUILD_HOST="Ubuntu"
          export KBUILD_BUILD_USER="Keinamvy"

          make O=out sweet_defconfig
          cat out/.config
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            LLVM=1 \
            LLVM_IAS=1 \
            AR=llvm-ar \
            NM=llvm-nm \
            LD=ld.lld \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi-


      - name: Fetch AnyKernel3
        run: |
          git clone --depth=1 https://github.com/MiDoNaSR545/anykernel3 -b main AnyKernel3
          cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: sweet-${{ env.ROM_TYPE }}-${{ env.KSU_TYPE }}-${{ env.BUILD_TIME }}
          path: AnyKernel3/*
